apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: nlp-pipeline

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
rules:
  # Allow the agent to access node information
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Permissions for node sub-resources (metrics, stats, etc.)
  - apiGroups: [""]
    resources: ["nodes/metrics", "nodes/stats", "nodes/proxy", "nodes/spec"]
    verbs: ["get"]

  # Other permissions for monitoring Kubernetes resources
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "list", "watch"]

  - nonResourceURLs: ["/metrics", "/metrics/cadvisor", "/stats", "/stats/summary"]
    verbs: ["get"]

  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
  - kind: ServiceAccount
    name: datadog-agent
    namespace: nlp-pipeline
