apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/home/ag7es/Documents/nlp-pipeline/nlp-pipeline-v5/text_db/texts"
