apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-pvc
  namespace: nlp-pipeline
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
